name = "PosDefManifoldML"
uuid = "a07f4532-e2c9-11e9-2ea2-6d98fe4a1f21"
authors = ["Marco-Congedo <marco.congedo@gmail.com>"]
version = "0.5.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Diagonalizations = "9cd687f3-b62d-43f3-8fd3-ffcd9e581047"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
GLMNet = "8d5ece8b-de18-5317-b113-243142960cc6"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PermutationTests = "dd25e4c7-56c0-4344-ab7a-80f9379a34f4"
PosDefManifold = "f45a3650-5c51-11e9-1e9a-133aa5e309cf"
PrecompileSignatures = "91cefc8d-f054-46dc-8f8c-26e11d7c5411"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataFrames = "1.7, 1.8"
Diagonalizations = "0.2"
Distributions = "0.22, 0.23, 0.24, 0.25"
Folds = "0.2.10"
GLMNet = "0.7"
LIBSVM = "0.8"
PermutationTests = "0.2"
PosDefManifold = "0.5"
PrecompileSignatures = "3.0"
Serialization = "1.11"
StatsAPI = "1.7"
StatsBase = "0.32, 0.33, 0.34"
julia = "1"

[extras]
PosDefManifold = "f45a3650-5c51-11e9-1e9a-133aa5e309cf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["PosDefManifold", "Statistics", "Test"]
